spring:
  datasource:
    username: burger_king
    password: whopper
    url: jdbc:mysql://localhost:3306/burger_king

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true